
update  PaymentDetailGeneralALL set CountDrug=((NameOfAssociatedCoveredDrugOrBiological1 <>" ")+ (NameOfAssociatedCoveredDrugOrBiological2 <>" ")+(NameOfAssociatedCoveredDrugOrBiological3 <>" ")+(                      NameOfAssociatedCoveredDrugOrBiological4 <>" ")) ;


Select TeachingHospitalID , TeachingHospitalName , PhysicianProfileID , PhysicianFirstName , PhysicianMiddleName , PhysicianLastName , PhysicianNameSuffix , RecipientPrimaryBusinessStreetAddressLine1 , RecipientPrimaryBusinessStreetAddressLine2 , RecipientCity , RecipientState , RecipientZipCode , RecipientCountry , RecipientProvince , RecipientPostalCode , PhysicianPrimaryType , PhysicianSpecialty                                     , PhysicianLicenseStateCode1 , PhysicianLicenseStateCode2 , PhysicianLicenseStateCode3 , PhysicianLicenseStateCode4 , SubmittingApplicableManufacturerOrApplicableGPOName , ApplicableManufacturerOrApplicableGPOMakingPaymentID , ApplicableManufacturerOrApplicableGPOMakingPaymentName , TotalAmountOfPaymentUSDollars/CountDrug  as PartialAmountOfPaymentUSDollars , DateOfPayment       , NumberOfPaymentsIncludedInTotalAmount/CountDrug as PartialNumberOfPaymentsIncludedInTotalAmount, NatureOfPaymentOrTransferOfValue , CityOfTravel , RecordID  , ProductIndicator , NameOfAssociatedCoveredDrugOrBiological1 , PhysicianLastNameDM , PhysicianFirstNameDM,CountDrug from PaymentDetailGeneralALL 
UNION
Select TeachingHospitalID , TeachingHospitalName , PhysicianProfileID , PhysicianFirstName , PhysicianMiddleName , PhysicianLastName , PhysicianNameSuffix , RecipientPrimaryBusinessStreetAddressLine1 , RecipientPrimaryBusinessStreetAddressLine2 , RecipientCity , RecipientState , RecipientZipCode , RecipientCountry , RecipientProvince , RecipientPostalCode , PhysicianPrimaryType , PhysicianSpecialty                                     , PhysicianLicenseStateCode1 , PhysicianLicenseStateCode2 , PhysicianLicenseStateCode3 , PhysicianLicenseStateCode4 , SubmittingApplicableManufacturerOrApplicableGPOName , ApplicableManufacturerOrApplicableGPOMakingPaymentID , ApplicableManufacturerOrApplicableGPOMakingPaymentName , TotalAmountOfPaymentUSDollars/CountDrug as PartialAmountOfPaymentUSDollars , DateOfPayment       , NumberOfPaymentsIncludedInTotalAmount/CountDrug as PartialNumberOfPaymentsIncludedInTotalAmount , NatureOfPaymentOrTransferOfValue , CityOfTravel , RecordID  , ProductIndicator , NameOfAssociatedCoveredDrugOrBiological2 , PhysicianLastNameDM , PhysicianFirstNameDM, CountDrug from PaymentDetailGeneralALL
UNION
Select TeachingHospitalID , TeachingHospitalName , PhysicianProfileID , PhysicianFirstName , PhysicianMiddleName , PhysicianLastName , PhysicianNameSuffix , RecipientPrimaryBusinessStreetAddressLine1 , RecipientPrimaryBusinessStreetAddressLine2 , RecipientCity , RecipientState , RecipientZipCode , RecipientCountry , RecipientProvince , RecipientPostalCode , PhysicianPrimaryType , PhysicianSpecialty                                     , PhysicianLicenseStateCode1 , PhysicianLicenseStateCode2 , PhysicianLicenseStateCode3 , PhysicianLicenseStateCode4 , SubmittingApplicableManufacturerOrApplicableGPOName , ApplicableManufacturerOrApplicableGPOMakingPaymentID , ApplicableManufacturerOrApplicableGPOMakingPaymentName , TotalAmountOfPaymentUSDollars/CountDrug as PartialAmountOfPaymentUSDollars , DateOfPayment       , NumberOfPaymentsIncludedInTotalAmount/CountDrug as PartialNumberOfPaymentsIncludedInTotalAmount , NatureOfPaymentOrTransferOfValue , CityOfTravel , RecordID  , ProductIndicator , NameOfAssociatedCoveredDrugOrBiological4 , PhysicianLastNameDM , PhysicianFirstNameDM, CountDrug from PaymentDetailGeneralALL
UNION
Select TeachingHospitalID , TeachingHospitalName , PhysicianProfileID , PhysicianFirstName , PhysicianMiddleName , PhysicianLastName , PhysicianNameSuffix , RecipientPrimaryBusinessStreetAddressLine1 , RecipientPrimaryBusinessStreetAddressLine2 , RecipientCity , RecipientState , RecipientZipCode , RecipientCountry , RecipientProvince , RecipientPostalCode , PhysicianPrimaryType , PhysicianSpecialty                                     , PhysicianLicenseStateCode1 , PhysicianLicenseStateCode2 , PhysicianLicenseStateCode3 , PhysicianLicenseStateCode4 , SubmittingApplicableManufacturerOrApplicableGPOName , ApplicableManufacturerOrApplicableGPOMakingPaymentID , ApplicableManufacturerOrApplicableGPOMakingPaymentName , TotalAmountOfPaymentUSDollars/CountDrug as PartialAmountOfPaymentUSDollars , DateOfPayment       , NumberOfPaymentsIncludedInTotalAmount/CountDrug as PartialNumberOfPaymentsIncludedInTotalAmount , NatureOfPaymentOrTransferOfValue , CityOfTravel , RecordID  , ProductIndicator , NameOfAssociatedCoveredDrugOrBiological4 , PhysicianLastNameDM , PhysicianFirstNameDM, CountDrug from PaymentDetailGeneralALL

|                    |                      | 316423             | LADLY              |                     | ABRAHAM           |                     | 5800 W 10                                  |                                            | LITTLE ROCK      | AR             | 72204            | United States    |                   |                     | Medical Doctor       | Allopathic & Osteopathic Physicians/ Internal Medicine/ Pulmonary Disease | AR                         |                            |                            |                            | Forest Laboratories, Inc.                           | 100000005529                                         | FOREST PHARMACEUTICALS, INC.                           |                            6.06 | 0000-00-00 00:00:00 |                                       0.5000 | Food and Beverage                                                                                                                                  |              | 100239910 | Covered          | TUDORZA                                  | APRHM               | LTL                  |         2 |